### ISSUE TITLE
[FEAT] GitHub Template 작업

### ISSUE THREAD

**Issue by newuserYejin** [ReCoderTeam/ReCoder_SubProject#22]
## 📌  To-do

git에서의 Template 만들기

- [x] issue template 만들기
- [x] discussion template 만들기
- [x] PR template 만들기
- [ ] mileston 연결

## ✨ connected things

- 각 template 사용방법 정일하기
- 팀원들 활용 방법 인지 정도 확인하기

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들, 참고 사이트 

- https://velog.io/@dohaeng0/GitHub-Project-Issue-%ED%99%9C%EC%9A%A9
